# Generated by Django 4.0.4 on 2022-10-25 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='is_service_selected',
            field=models.BooleanField(default=False),
        ),
    ]
