# Generated by Django 4.0.4 on 2022-10-25 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_services_is_service_selected'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_enable', models.BooleanField(default=True)),
            ],
        ),
    ]
